#version 430 core

layout (r32f, binding = 0) readonly uniform image2D WATER_PING;
layout (r32f, binding = 1) writeonly uniform image2D WATER_PONG;

layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

uniform float TIME;

void main(void)
{
	ivec2 uv = ivec2(gl_GlobalInvocationID.xy);

	const float Ke = 0.02; // evaporation constant Ke

	float d2 = imageLoad(WATER_PING, uv).r;

	float dt = d2 * (1.f - Ke * TIME);

	imageStore(WATER_PONG, uv, vec4(dt));
}
